<?php
/**
 * @var \Kir\Module\Block\Test $block
 */

echo $block->testmessage("Hello, Kir");?>
<div class="form-test" data-bind="scope:'library'">

<form class="jsknout" id="test-jsknout" >
  <p><b>Your name</b><br>
   <input type="text" name="name" size="40" data-bind = "value: name, valueUpdate: 'afterkeydown'" />
  </p>
    <p>Your name is : <span data-bind="text:getName"></span></p>
    <p>Your name afterkeydown : <span data-bind = "text: name, style: {fontWeight:font() < 0 ? 'unset' : 'bold'}"></span></p>

    <button type="button" data-bind="click: onSubmit" class="action">Send</button>
 </form>
</div>
<script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "library": {
                            "component": "Kir_Module/js/library"
                        }
                    }
                }
            }
        }
</script>
