<section class="vertical-center slider">
    <div>
        <img src="http://placehold.it/350x100?text=1">
    </div>
    <div>
        <img src="http://placehold.it/350x100?text=2">
    </div>
    <div>
        <img src="http://placehold.it/350x100?text=3">
    </div>
    <div>
        <img src="http://placehold.it/350x100?text=4">
    </div>
    <div>
        <img src="http://placehold.it/350x100?text=5">
    </div>
    <div>
        <img src="http://placehold.it/350x100?text=6">
    </div>
    <div>
        <img src="http://placehold.it/350x100?text=7">
    </div>
    <div>
        <img src="http://placehold.it/350x100?text=8">
    </div>
    <div>
        <img src="http://placehold.it/350x100?text=9">
    </div>
    <div>
        <img src="http://placehold.it/350x100?text=10">
    </div>
</section>


<script type="text/javascript">
    require(['jquery','slick'],function($){
        $(".vertical-center").slick({
            dots: true,
            vertical: true,
            centerMode: true,
        });
    });
</script>