<section class="slider">
    <h3>Slider Widget</h3>
    <?php
    $imageCount = $block->getData('slides');
    $imageChooser = $block->getData('images');
    if (count($imageCount) > 0) {
        ?>
        <div class="vertical-center" data-mage-init='{"init": {}}'>
            <?php
            for ($i = 0; $i < $imageCount; $i++) {
                ?>
                <div><img src="<?php echo $block->getMediaUrl().$imageChooser;?>"></div>
                <?php
            }
            ?>
        </div>
        <?php
    }
    ?>

</section>


