<section class="slider">
    <h3>Slider Widget</h3>
    <?php
    $imageCount = $block->getData('slides');
    $imageChooser = $block->getData('images');
    if (count($imageCount) > 0) {
        ?>
        <div class="vertical-center">
            <?php
            for ($i = 0; $i < $imageCount; $i++) {
                ?>
                <div><img src="<?php echo $imageChooser;?>"></div>
                <?php
            }
            ?>
        </div>
        <?php
    }
    ?>

</section>


<script type="text/javascript">
    require(['jquery','slick'],function($){
        $(".vertical-center").slick({
            dots: true,
            vertical: false,
            centerMode: true,
        });
    });
</script>